# Generated by Django 5.0.6 on 2024-11-29 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0011_grade_unit_unitprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
