# Generated by Django 5.0.6 on 2024-11-29 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0015_alter_knowledgenode_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgenode',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='question',
            name='node',
            field=models.CharField(max_length=255),
        ),
    ]
