# Generated by Django 5.0.6 on 2024-11-29 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0016_alter_knowledgenode_id_alter_question_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='knowledge.knowledgenode'),
        ),
    ]
