# Generated by Django 5.0.6 on 2024-11-29 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0018_alter_knowledgenode_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgecomponent',
            name='node',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
