# Generated by Django 5.0.6 on 2024-11-29 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0019_alter_knowledgecomponent_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='node',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
