# Generated by Django 5.0.6 on 2024-11-29 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0021_alter_knowledgenode_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresponse',
            name='quiz_attempt',
        ),
        migrations.RemoveField(
            model_name='quizresponse',
            name='question',
        ),
        migrations.AddField(
            model_name='unitprogress',
            name='last_attempt_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unitprogress',
            name='quiz_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unitprogress',
            name='quiz_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='knowledgecomponent',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='knowledge.knowledgenode'),
        ),
        migrations.AlterField(
            model_name='question',
            name='node',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='QuizAttempt',
        ),
        migrations.DeleteModel(
            name='QuizResponse',
        ),
    ]
